# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Cache-Cache
version:      1.05
version_from: lib/Cache/Cache.pm
installdirs:  site
requires:
    Digest::SHA1:                  2.02
    Error:                         0.15
    File::Spec:                    0.82
    Storable:                      1.014

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
